# Generated by Django 5.0.4 on 2024-05-01 18:18

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):
  dependencies = [
    ("event", "0002_event_location_alter_event_participants"),
  ]

  operations = [
    migrations.RenameField(
      model_name="event",
      old_name="location",
      new_name="location_name",
    ),
    migrations.AddField(
      model_name="event",
      name="location_coordinates",
      field=django.contrib.gis.db.models.fields.PointField(
        # Lamia's Coordinates. Birthplace of Ridly.com ;-)
        default=django.contrib.gis.geos.point.Point(22.4337, 38.8997),
        srid=4326,
      ),
      preserve_default=False,
    ),
  ]
