# Docker Compose only used for development.

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: ridly_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    volumes:
      - ridly_db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  api:
    container_name: ridly_api
    build:
      context: .
      dockerfile: Dockerfile.api
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
volumes:
  ridly_db_data:
