version: '3.2'
services:
  db:
    image: postgres
    container_name: ridl_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    volumes:
      - ridl_db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  ridl_db_data:
