# Docker Compose only used for development.

services:
  db:
    image: postgis/postgis:16-3.4-alpine
    container_name: ridly_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    volumes:
      - ridly_db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis/redis-stack-server:7.2.0-v6
    container_name: ridly_redis
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - ridly_redis_data:/data
  api:
    container_name: ridly_api
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  swagger:
    image: swaggerapi/swagger-ui
    container_name: ridly_swagger
    ports:
      - "80:8001"
    environment:
      SWAGGER_JSON: /schema.yml
    volumes:
      - ./schema.yml:/schema.yml
volumes:
  ridly_db_data:
  ridly_redis_data:
