openapi: 3.0.3
info:
  title: Ridly API
  version: 1.0.0
  description: Outdoor Treasure Hunt
paths:
  /event/{id}/:
    get:
      operationId: event
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - event
      security:
      - cookieAuth: []
      - JWTAuthentication: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
          description: ''
  /event/{id}/join/:
    post:
      operationId: join_event
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - event
      security:
      - cookieAuth: []
      - JWTAuthentication: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventJoin'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
          description: ''
  /event/joined/:
    get:
      operationId: joined_events
      tags:
      - event
      security:
      - cookieAuth: []
      - JWTAuthentication: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
          description: ''
  /event/upcoming/:
    get:
      operationId: upcoming_events
      parameters:
      - in: query
        name: distance
        schema:
          type: integer
        description: Distance in km from user's last known location
      tags:
      - event
      security:
      - cookieAuth: []
      - JWTAuthentication: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
          description: ''
  /hunt/{id}/:
    get:
      operationId: hunt
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - hunt
      security:
      - cookieAuth: []
      - JWTAuthentication: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hunt'
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
          description: ''
  /hunt/{id}/clue/{clue_order}/:
    get:
      operationId: hunt_clue
      parameters:
      - in: path
        name: clue_order
        schema:
          type: integer
        required: true
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - hunt
      security:
      - cookieAuth: []
      - JWTAuthentication: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HuntClue'
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
          description: ''
  /oauth/{provider}/login/:
    post:
      operationId: oauth_login
      parameters:
      - in: path
        name: provider
        schema:
          type: string
          enum:
          - google
        description: OAuth provider name
        required: true
      tags:
      - oauth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Login'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      security:
      - cookieAuth: []
      - JWTAuthentication: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
          description: ''
  /user/complete-signup/:
    put:
      operationId: user_complete_signup
      tags:
      - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompleteSignup'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CompleteSignup'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CompleteSignup'
        required: true
      security:
      - cookieAuth: []
      - JWTAuthentication: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompleteSignup'
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
          description: ''
  /user/logout/:
    delete:
      operationId: user_logout
      tags:
      - user
      security:
      - cookieAuth: []
      - JWTAuthentication: []
      responses:
        '204':
          description: No response body
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
          description: ''
  /user/me/:
    get:
      operationId: user_me
      tags:
      - user
      security:
      - cookieAuth: []
      - JWTAuthentication: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
          description: ''
  /user/profile/{id}/:
    get:
      operationId: getUserProfile
      description: Get user's profile along with their 5 first joined events
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - user
      security:
      - cookieAuth: []
      - JWTAuthentication: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserProfile'
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
          description: ''
  /user/update/location/:
    put:
      operationId: user_update_last_known_location
      tags:
      - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateLastKnownLocation'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UpdateLastKnownLocation'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UpdateLastKnownLocation'
        required: true
      security:
      - cookieAuth: []
      - JWTAuthentication: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateLastKnownLocation'
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
          description: ''
components:
  schemas:
    CompleteSignup:
      type: object
      properties:
        username:
          type: string
          maxLength: 50
        did_complete_signup:
          type: boolean
          readOnly: true
      required:
      - did_complete_signup
      - username
    Creator:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/PublicUser'
      required:
      - user
    DetailedError:
      type: object
      properties:
        detail:
          type: string
    Event:
      type: object
      description: Full event serializer.
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 50
        description:
          type: string
        creator:
          $ref: '#/components/schemas/Creator'
        participant_avatars:
          type: array
          items:
            type: string
          description: Get the first 3 participants' avatars, excluding the logged
            in user and users without avatars.
          readOnly: true
        participant_count:
          type: integer
          maximum: 2147483647
          minimum: 0
        has_joined:
          type: boolean
          readOnly: true
        location_name:
          type: string
          maxLength: 100
        happening_at:
          type: string
          format: date-time
        hunt_id:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - creator
      - description
      - happening_at
      - has_joined
      - hunt_id
      - id
      - location_name
      - name
      - participant_avatars
    EventJoin:
      type: object
      properties:
        has_joined:
          type: boolean
        participant_count:
          type: integer
      required:
      - has_joined
      - participant_count
    GetUserProfile:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/UserWithProfile'
        joined_events:
          type: array
          items:
            $ref: '#/components/schemas/MiniEvent'
      required:
      - joined_events
      - user
    Hunt:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        event:
          $ref: '#/components/schemas/HuntEvent'
        clue_count:
          type: integer
          readOnly: true
      required:
      - clue_count
      - event
      - id
    HuntClue:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        riddle:
          type: string
          maxLength: 1000
        order:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        location_threshold:
          type: number
          format: double
      required:
      - id
      - riddle
    HuntEvent:
      type: object
      properties:
        name:
          type: string
          maxLength: 50
        location_name:
          type: string
          maxLength: 100
        location_coordinates:
          $ref: '#/components/schemas/Point'
      required:
      - location_coordinates
      - location_name
      - name
    Login:
      type: object
      properties:
        token:
          type: string
      required:
      - token
    MiniEvent:
      type: object
      description: Event serializer, but with only the necessary fields.
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 50
        has_joined:
          type: boolean
          readOnly: true
        location_name:
          type: string
          maxLength: 100
        participant_count:
          type: integer
          maximum: 2147483647
          minimum: 0
        happening_at:
          type: string
          format: date-time
      required:
      - happening_at
      - has_joined
      - id
      - location_name
      - name
    Point:
      type: object
      description: Serializer for django.contrib.gis.geos.Point
      properties:
        long:
          type: number
          format: double
        lat:
          type: number
          format: double
      required:
      - lat
      - long
    PublicUser:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        first_name:
          type: string
          maxLength: 50
        last_name:
          type: string
          maxLength: 50
        username:
          type: string
          maxLength: 50
        is_creator:
          type: boolean
        avatar_url:
          type: string
          format: uri
      required:
      - avatar_url
      - first_name
      - id
      - last_name
      - username
    UpdateLastKnownLocation:
      type: object
      properties:
        last_known_location:
          $ref: '#/components/schemas/Point'
      required:
      - last_known_location
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        first_name:
          type: string
          maxLength: 50
        last_name:
          type: string
          maxLength: 50
        username:
          type: string
          maxLength: 50
        email:
          type: string
          format: email
          maxLength: 254
        avatar_url:
          type: string
          format: uri
        did_complete_signup:
          type: boolean
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - avatar_url
      - created_at
      - email
      - first_name
      - id
      - last_name
      - username
    UserProfile:
      type: object
      properties:
        bio:
          type: string
    UserWithProfile:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        first_name:
          type: string
          maxLength: 50
        last_name:
          type: string
          maxLength: 50
        username:
          type: string
          maxLength: 50
        is_creator:
          type: boolean
        avatar_url:
          type: string
          format: uri
        profile:
          $ref: '#/components/schemas/UserProfile'
      required:
      - avatar_url
      - first_name
      - id
      - last_name
      - profile
      - username
    ValidationError:
      type: object
      properties:
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
      required:
      - errors
  securitySchemes:
    JWTAuthentication:
      type: apiKey
      in: header
      name: x-access-token
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
