# Generated by Django 5.0.4 on 2024-06-21 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards(apps, _):
  UserProfile = apps.get_model("profile", "UserProfile")
  User = apps.get_model("user", "User")

  for user in User.objects.all():
    UserProfile.objects.create(user=user)


def backwards(apps, _):
  pass


class Migration(migrations.Migration):
  initial = True

  dependencies = [
    ("user", "0005_remove_user_avatar_url_and_more"),
  ]

  operations = [
    migrations.CreateModel(
      name="UserProfile",
      fields=[
        (
          "user",
          models.OneToOneField(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="profile",
            primary_key=True,
            serialize=False,
            to=settings.AUTH_USER_MODEL,
          ),
        ),
        ("bio", models.TextField(blank=True)),
      ],
    ),
    migrations.RunPython(forwards, backwards),
  ]
