# Generated by Django 5.0.4 on 2024-05-01 11:18

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):
  dependencies = []

  operations = [CreateExtension("postgis")]
