# Generated by Django 5.0.4 on 2024-05-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurehuntclue',
            name='location_threshold',
            field=models.FloatField(default=50),
        ),
    ]
