# Generated by Django 5.0.4 on 2024-05-09 11:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_rename_location_event_location_name_and_more'),
        ('hunt', '0004_treasurehuntclue_is_last_treasurehuntcluestat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TreasureHunt',
            new_name='Hunt',
        ),
        migrations.RenameModel(
            old_name='TreasureHuntClue',
            new_name='HuntClue',
        ),
        migrations.RenameModel(
            old_name='TreasureHuntClueStat',
            new_name='HuntClueStat',
        ),
    ]
