# Generated by Django 5.0.4 on 2024-06-15 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_rename_location_event_location_name_and_more'),
        ('hunt', '0007_add_huntcluestat_hunt_stat_and_migrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunt',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
