# Generated by Django 5.0.4 on 2024-06-15 18:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_did_complete_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_known_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
