# Generated by Django 5.0.4 on 2024-06-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_last_known_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_url',
        ),
    ]
