# Generated by Django 5.0.4 on 2024-06-22 16:10

from django.db import migrations, models


def forwards(apps, _):
  Creator = apps.get_model("creator", "Creator")
  for creator in Creator.objects.all():
    creator.user.is_creator = True
    creator.user.save()


def backwards(apps, _):
  pass


class Migration(migrations.Migration):
  dependencies = [
    ("user", "0005_remove_user_avatar_url_and_more"),
  ]

  operations = [
    migrations.AddField(
      model_name="user",
      name="is_creator",
      field=models.BooleanField(default=False),
    ),
    migrations.RunPython(forwards, backwards),
  ]
